import React, { createContext, useContext, useState } from 'react';

const translations = {
  sk: {
    // Navigation
    dashboard: "Dashboard",
    leads: "Leady",
    properties: "Nehnuteľnosti",
    clients: "Klienti",
    calendar: "Kalendár",
    commissions: "Provízie",
    referrers: "Tiperi",
    partners: "Partneri",
    realEstateAgencies: "Realitné kancelárie",
    reports: "Reporty",
    map: "Mapa",
    team: "Tím",
    publicSite: "Verejný web",

    // Common
    search: "Hľadať",
    add: "Pridať",
    edit: "Upraviť",
    delete: "Vymazať",
    save: "Uložiť",
    cancel: "Zrušiť",
    close: "Zavrieť",
    back: "Späť",
    loading: "Načítavam...",
    total: "Celkom",
    active: "Aktívny",
    inactive: "Neaktívny",
    status: "Status",
    name: "Meno",
    email: "Email",
    phone: "Telefón",
    city: "Mesto",
    country: "Krajina",
    notes: "Poznámky",
    detail: "Detail",
    allStatuses: "Všetky statusy",
    noResultsFound: "Nenašli sa žiadne výsledky",
    of: "z",

    // Dashboard stats
    newLeads: "Nové leady",
    waiting: "čaká",
    totalClients: "Celkom klientov",
    activeCount: "aktívnych",
    availableCount: "dostupných",
    referrerLeads: "Leady od tiperov",
    fromPartners: "od partnerov",
    closedDeals: "Uzavreté obchody",
    successful: "úspešných",
    reminders: "Pripomienky",
    pending: "Čaká",

    // Lead statuses
    new_lead: "Nový lead",
    unclaimed: "Neprevzatý",
    claimed: "Prevzatý",
    contacted: "Kontaktovaný",
    qualified: "Kvalifikovaný",
    offers_sent: "Ponuky odoslané",
    viewing: "Obhliadka",
    reserved: "Rezervácia",
    closed: "Uzavretý",
    lost: "Stratený",

    // Leads page
    newLeadsCount: "Nové",
    myLeads: "Moje leady",
    claimedCount: "Prevzaté",
    fromReferrers: "Od tiperov",
    allLeadsTab: "Všetky",
    newLeadsTab: "Nové",
    unclaimedTab: "Neprevzaté",
    myLeadsTab: "Moje",
    searchLeads: "Hľadať leady...",
    allSources: "Všetky zdroje",
    claimLead: "Prevziať",
    noLeadsFound: "Nenašli sa žiadne leady",
    myLead: "Môj lead",
    newLead: "Nový lead",

    // Clients page
    addClient: "Pridať klienta",
    searchClients: "Hľadať klientov...",
    noClientsFound: "Nenašli sa žiadni klienti",
    logInteraction: "Zaznamenať interakciu",
    budget: "Rozpočet",
    clients: "klientov",
    deleteClientConfirm: "Vymazať klienta",

    // Calendar page
    upcoming: "Nadchádzajúce",
    overdue: "Po termíne",
    completed: "Dokončené",
    all: "Všetky",
    newReminder: "Nová pripomienka",
    noRemindersFound: "Nenašli sa žiadne pripomienky",
    today: "Dnes",
    tomorrow: "Zajtra",
    overdueLabel: "Po termíne",
    done: "Hotovo",

    // Properties page
    propertiesByCountry: "Nehnuteľnosti podľa krajín",
    selectCountryToView: "Vyberte krajinu pre zobrazenie ponúk",
    allCountriesBack: "Všetky krajiny",
    addProperty: "Pridať nehnuteľnosť",
    searchProperties: "Hľadať nehnuteľnosti...",
    noPropertiesInCountry: "Žiadne nehnuteľnosti v",
    addFirstProperty: "Pridať prvú nehnuteľnosť",
    selected: "Vybrané",
    deleteSelected: "Vymazať vybratých",
    offers: "ponúk",
    available: "Dostupné",
    sold: "Predané",
    offMarket: "Off Market",
    propertyType: "Typ",
    bedrooms: "Spálne",
    bathrooms: "Kúpeľne",
    area: "Plocha",
    features: "Vlastnosti",
    sendBrochure: "Poslať brožúru",
    propertiesFound: "nehnuteľností nájdených",
    noPropertiesFound: "Nenašli sa žiadne nehnuteľnosti",

    // Commissions page
    earned: "Zarobené",
    pendingAmount: "Čakajúce",
    totalDeals: "Celkom obchodov",
    recordCommission: "Zaznamenať províziu",
    property: "Nehnuteľnosť",
    client: "Klient",
    salePrice: "Predajná cena",
    commissionRate: "Sadzba",
    commission: "Provízia",
    date: "Dátum",
    noCommissionsYet: "Žiadne provízie",
    selectCountryLabel: "Krajina",
    selectCountryPlaceholder: "Vybrať krajinu",
    projectLabel: "Projekt / Nehnuteľnosť",
    selectProject: "Vybrať projekt",
    selectCountryFirst: "Najprv vybrať krajinu",
    commissionType: "Typ provízie",
    percentageType: "Percentuálna (%)",
    absoluteType: "Absolútna hodnota (€)",
    commissionRateLabel: "Sadzba provízie (%)",
    commissionAmountLabel: "Výška provízie (€)",
    totalCommissionLabel: "Celková provízia",
    dealDate: "Dátum obchodu",
    referrer: "Referrer",
    company: "Firma",
    invoiced: "Fakturované",
    paid: "Zaplatené",
    statusUpdated: "Status aktualizovaný",
    commissionRecorded: "Provízia zaznamenaná",

    // Team page
    teamTitle: "Tím",
    manageTeamSubtitle: "Spravujte členov tímu a ich prístupy",
    inviteMember: "Pozvať člena",
    teamMembers: "Členovia tímu",
    noTeamMembers: "Žiadni členovia tímu",
    inviteNewMember: "Pozvať nového člena",
    emailAddress: "Email adresa *",
    role: "Rola",
    inviteInfo: "Používateľ dostane e-mail s pozvánkou a môže sa prihlásiť do systému.",
    sendInvitation: "Odoslať pozvánku",
    members: "členov",
    invitationSent: "Pozvánka odoslaná na",
    roleUpdated: "Rola aktualizovaná",
    adminDesc: "Plný prístup ku všetkému",
    agentDesc: "Prístup k nehnuteľnostiam a klientom",
    tiperDesc: "Prístup len k sekcii Tiper",
    partnerDesc: "Prístup len k sekcii Partner",

    // Reports page
    reporting: "Reporting & Analytics",
    performanceOverview: "Prehľad výkonnosti a štatistík",
    totalRevenue: "Celkový príjem",
    avgDealSize: "Priemerný obchod",
    conversionRate: "Konverzia",
    leadSources: "Zdroje leadov",
    countries: "Krajiny",
    teamPerformance: "Výkonnosť tímu",
    referrerPerformance: "Výkonnosť tiperov",
    source: "Zdroj",
    totalLeads: "Celkom leadov",
    closedTable: "Uzavreté",
    lostTable: "Stratené",
    assignedLeads: "Pridelené leady",
    closedDealsTable: "Uzavreté dealy",
    code: "Kód",
    leadsBySource: "Leady podľa zdrojov",
    leadsByCountry: "Leady podľa krajín",
    teamPerformanceTitle: "Výkonnosť asistentiek / tímu",
    referrerPerformanceTitle: "Výkonnosť tiperov",

    // Real Estate Agencies
    realEstateAgenciesTitle: "Realitné kancelárie",
    partnerAgencies: "Partneri – realitné kancelárie prinášajúce klientov",
    addAgency: "Pridať kanceláriu",
    searchAgency: "Hľadať kanceláriu...",
    activeAgencies: "Aktívne",
    editAgency: "Upraviť kanceláriu",
    newAgency: "Nová realitná kancelária",
    agencyName: "Názov kancelárie *",
    contactPerson: "Kontaktná osoba",
    web: "Web",
    agreedCommission: "Dohodnutá provízia (%)",
    partnershipNotes: "Podmienky spolupráce / poznámky",
    partnershipNotesPlaceholder: "Popis dohodnutých podmienok, provízií, spôsobu spolupráce...",
    addFirstAgency: "Pridať prvú kanceláriu",
    noAgencies: "Žiadne realitné kancelárie",
    partnershipConditions: "Podmienky spolupráce:",
    commissionLabel: "Provízia:",
    activeAgency: "Aktívna",
    inactiveAgency: "Neaktívna",
    agencyUpdated: "Kancelária aktualizovaná",
    agencyAdded: "Kancelária pridaná",
    agencyNameRequired: "Zadajte názov kancelárie",
    agencyNamePlaceholder: "Realitná kancelária XY",
    partnershipNotesLabel: "Podmienky spolupráce / poznámky",

    // Reminder types
    type_viewing: "Obhliadka",
    type_contract_renewal: "Predĺženie zmluvy",
    type_follow_up: "Sledovanie",
    type_payment: "Platba",
    type_other: "Iné",
    // Priorities
    priority_low: "Nízka",
    priority_medium: "Stredná",
    priority_high: "Vysoká",
    // Reminder form
    reminderTitle: "Názov *",
    reminderType: "Typ",
    reminderPriority: "Priorita",
    reminderDueDate: "Dátum a čas",
    reminderDescription: "Popis",
    optional: "Voliteľné",
    reminderCreated: "Pripomienka vytvorená",
    create: "Vytvoriť",

    // Extra
    claimSuccess: "Lead úspešne prevzatý",
    clientDeleted: "Klient vymazaný",
    revenue: "Provízie",
    referrerCol: "Tiper",
    conversionRateCol: "Konverzia",
    noData: "Žiadne dáta",
  },
  en: {
    // Navigation
    dashboard: "Dashboard",
    leads: "Leads",
    properties: "Properties",
    clients: "Clients",
    calendar: "Calendar",
    commissions: "Commissions",
    referrers: "Referrers",
    partners: "Partners",
    realEstateAgencies: "Real Estate Agencies",
    reports: "Reports",
    map: "Map",
    team: "Team",
    publicSite: "Public Site",

    // Common
    search: "Search",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    loading: "Loading...",
    total: "Total",
    active: "Active",
    inactive: "Inactive",
    status: "Status",
    name: "Name",
    email: "Email",
    phone: "Phone",
    city: "City",
    country: "Country",
    notes: "Notes",
    detail: "Detail",
    allStatuses: "All Statuses",
    noResultsFound: "No results found",
    of: "of",

    // Dashboard stats
    newLeads: "New Leads",
    waiting: "waiting",
    totalClients: "Total Clients",
    activeCount: "active",
    availableCount: "available",
    referrerLeads: "Referrer Leads",
    fromPartners: "from partners",
    closedDeals: "Closed Deals",
    successful: "successful",
    reminders: "Reminders",
    pending: "Pending",

    // Lead statuses
    new_lead: "New Lead",
    unclaimed: "Unclaimed",
    claimed: "Claimed",
    contacted: "Contacted",
    qualified: "Qualified",
    offers_sent: "Offers Sent",
    viewing: "Viewing",
    reserved: "Reserved",
    closed: "Closed",
    lost: "Lost",

    // Leads page
    newLeadsCount: "New",
    myLeads: "My Leads",
    claimedCount: "Claimed",
    fromReferrers: "From Referrers",
    allLeadsTab: "All",
    newLeadsTab: "New",
    unclaimedTab: "Unclaimed",
    myLeadsTab: "Mine",
    searchLeads: "Search leads...",
    allSources: "All Sources",
    claimLead: "Claim",
    noLeadsFound: "No leads found",
    myLead: "My lead",
    newLead: "New Lead",

    // Clients page
    addClient: "Add Client",
    searchClients: "Search clients...",
    noClientsFound: "No clients found",
    logInteraction: "Log Interaction",
    budget: "Budget",
    clients: "clients",
    deleteClientConfirm: "Delete client",

    // Calendar page
    upcoming: "Upcoming",
    overdue: "Overdue",
    completed: "Completed",
    all: "All",
    newReminder: "New Reminder",
    noRemindersFound: "No reminders found",
    today: "Today",
    tomorrow: "Tomorrow",
    overdueLabel: "Overdue",
    done: "Done",

    // Properties page
    propertiesByCountry: "Properties by Country",
    selectCountryToView: "Select a country to view listings",
    allCountriesBack: "All Countries",
    addProperty: "Add Property",
    searchProperties: "Search properties...",
    noPropertiesInCountry: "No properties in",
    addFirstProperty: "Add First Property",
    selected: "Selected",
    deleteSelected: "Delete Selected",
    offers: "listings",
    available: "Available",
    sold: "Sold",
    offMarket: "Off Market",
    propertyType: "Type",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    area: "Area",
    features: "Features",
    sendBrochure: "Send Brochure",
    propertiesFound: "properties found",
    noPropertiesFound: "No properties found",

    // Commissions page
    earned: "Earned",
    pendingAmount: "Pending",
    totalDeals: "Total Deals",
    recordCommission: "Record Commission",
    property: "Property",
    client: "Client",
    salePrice: "Sale Price",
    commissionRate: "Rate",
    commission: "Commission",
    date: "Date",
    noCommissionsYet: "No commissions yet",
    selectCountryLabel: "Country",
    selectCountryPlaceholder: "Select country",
    projectLabel: "Project / Property",
    selectProject: "Select project",
    selectCountryFirst: "Select country first",
    commissionType: "Commission Type",
    percentageType: "Percentage (%)",
    absoluteType: "Fixed Amount (€)",
    commissionRateLabel: "Commission Rate (%)",
    commissionAmountLabel: "Commission Amount (€)",
    totalCommissionLabel: "Total Commission",
    dealDate: "Deal Date",
    referrer: "Referrer",
    company: "Company",
    invoiced: "Invoiced",
    paid: "Paid",
    statusUpdated: "Status updated",
    commissionRecorded: "Commission recorded",

    // Team page
    teamTitle: "Team",
    manageTeamSubtitle: "Manage team members and their access levels",
    inviteMember: "Invite Member",
    teamMembers: "Team Members",
    noTeamMembers: "No team members",
    inviteNewMember: "Invite New Member",
    emailAddress: "Email address *",
    role: "Role",
    inviteInfo: "The user will receive an invitation email and can log into the system.",
    sendInvitation: "Send Invitation",
    members: "members",
    invitationSent: "Invitation sent to",
    roleUpdated: "Role updated",
    adminDesc: "Full access to everything",
    agentDesc: "Access to properties and clients",
    tiperDesc: "Access only to the Referrer section",
    partnerDesc: "Access only to the Partner section",

    // Reports page
    reporting: "Reporting & Analytics",
    performanceOverview: "Performance overview and statistics",
    totalRevenue: "Total Revenue",
    avgDealSize: "Avg Deal Size",
    conversionRate: "Conversion Rate",
    leadSources: "Lead Sources",
    countries: "Countries",
    teamPerformance: "Team Performance",
    referrerPerformance: "Referrer Performance",
    source: "Source",
    totalLeads: "Total Leads",
    closedTable: "Closed",
    lostTable: "Lost",
    assignedLeads: "Assigned Leads",
    closedDealsTable: "Closed Deals",
    code: "Code",
    leadsBySource: "Leads by Source",
    leadsByCountry: "Leads by Country",
    teamPerformanceTitle: "Team / Agent Performance",
    referrerPerformanceTitle: "Referrer Performance",

    // Reminder types
    type_viewing: "Viewing",
    type_contract_renewal: "Contract Renewal",
    type_follow_up: "Follow Up",
    type_payment: "Payment",
    type_other: "Other",
    // Priorities
    priority_low: "Low",
    priority_medium: "Medium",
    priority_high: "High",
    // Reminder form
    reminderTitle: "Title *",
    reminderType: "Type",
    reminderPriority: "Priority",
    reminderDueDate: "Due Date & Time",
    reminderDescription: "Description",
    optional: "Optional",
    reminderCreated: "Reminder created",
    create: "Create",

    // Extra
    claimSuccess: "Lead successfully claimed",
    clientDeleted: "Client deleted",
    revenue: "Revenue",
    referrerCol: "Referrer",
    conversionRateCol: "Conversion",
    noData: "No data",

    // Real Estate Agencies
    realEstateAgenciesTitle: "Real Estate Agencies",
    partnerAgencies: "Partner agencies bringing clients",
    addAgency: "Add Agency",
    searchAgency: "Search agency...",
    activeAgencies: "Active",
    editAgency: "Edit Agency",
    newAgency: "New Real Estate Agency",
    agencyName: "Agency Name *",
    contactPerson: "Contact Person",
    web: "Website",
    agreedCommission: "Agreed Commission (%)",
    partnershipNotes: "Partnership Terms / Notes",
    partnershipNotesPlaceholder: "Description of agreed terms, commissions, cooperation details...",
    addFirstAgency: "Add First Agency",
    noAgencies: "No real estate agencies",
    partnershipConditions: "Partnership terms:",
    commissionLabel: "Commission:",
    activeAgency: "Active",
    inactiveAgency: "Inactive",
    agencyUpdated: "Agency updated",
    agencyAdded: "Agency added",
    agencyNameRequired: "Please enter agency name",
    agencyNamePlaceholder: "Real Estate Agency XY",
    partnershipNotesLabel: "Partnership Terms / Notes",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'sk');

  const changeLanguage = (lang) => {
    localStorage.setItem('language', lang);
    setLanguage(lang);
  };

  const t = (key) => translations[language]?.[key] || translations['sk']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ t, language, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within LanguageProvider');
  return context;
};