import React, { createContext, useContext, useState } from "react";

const t = {
  ru: {
    offers: "Предложения",
    contact: "Контакт",
    backToOffers: "Вернуться к предложениям",
    heroTitle: "Роскошная недвижимость",
    heroTitleHighlight: "за границей",
    heroSubtitle: "Инвестируйте в премиальные проекты в лучших направлениях мира",
    allCountries: "Все страны",
    allTypes: "Все типы",
    minPrice: "Мин. цена (€)",
    maxPrice: "Макс. цена (€)",
    apartment: "Квартира",
    villa: "Вилла",
    penthouse: "Пентхаус",
    studio: "Студия",
    townhouse: "Таунхаус",
    availableOffers: "Доступные предложения",
    properties: "свойств",
    noProperties: "Свойства не найдены",
    detail: "Подробнее",
    bedrooms: "Спальни",
    bathrooms: "Ванные комнаты",
    description: "Описание",
    amenities: "Удобства",
    available_units: "Доступные единицы",
    interested: "Я заинтересован",
    nameSurname: "Имя и фамилия *",
    email: "Электронная почта *",
    phone: "Телефон *",
    minBudget: "Мин. бюджет (€)",
    maxBudget: "Макс. бюджет (€)",
    message: "Ваше сообщение",
    gdpr: "Я прочитал и согласен с ",
    gdprLink: "политикой защиты персональных данных (GDPR)",
    gdprEnd: ". Я согласен на обработку моих персональных данных в целях ответа на мой запрос. *",
    send: "Отправить запрос",
    sending: "Отправка...",
    listProperty: "Списать недвижимость",
    submitTitle: "Опубликуйте вашу недвижимость",
    submitSubtitle: "Введите детали - объявление будет доступно на всех языках",
    submitBadge: "Бесплатное размещение, одобряем в течение 48 часов",
    ownerInfo: "Контактные данные",
    ownerName: "Имя и фамилия",
    ownerEmail: "Электронная почта",
    ownerPhone: "Телефон",
    propertyInfo: "Детали недвижимости",
    writingIn: "Пишу на языке",
    propertyTitleLabel: "Название недвижимости",
    selectCountry: "Выберите страну",
    cityLabel: "Город / область",
    typeLabel: "Тип недвижимости",
    priceLabel: "Цена",
    bedroomsLabel: "Спальни",
    bathroomsLabel: "Ванные комнаты",
    descriptionLabel: "Описание недвижимости",
    autoTranslateNote: "Описание автоматически переведем на SK и EN",
    photosLabel: "Фотографии",
    uploadPhotos: "Нажмите или перетащите фотографии (макс 10)",
    submitBtn: "Отправить на утверждение",
    translatingListing: "Переводим вашу недвижимость...",
    translatingListingSub: "ИИ переводит содержание на словацкий и английский языки",
    submitSuccessTitle: "Спасибо за объявление!",
    submitSuccessText: "Мы получили ваше объявление и опубликуем его после проверки. Мы уведомим вас по электронной почте.",
    backToHome: "На главную",
    exploreMap: "Исследуйте наши направления",
    exploreMapSub: "Нажмите на булавку страны, чтобы отфильтровать предложения по местоположению",
    rights: "Все права защищены.",
    privacy: "Политика конфиденциальности (GDPR)",
  },
  de: {
    offers: "Angebote",
    contact: "Kontakt",
    backToOffers: "Zurück zu den Angeboten",
    heroTitle: "Luxusimmobilien",
    heroTitleHighlight: "im Ausland",
    heroSubtitle: "Investieren Sie in Premium-Projekte an den besten Zielen der Welt",
    allCountries: "Alle Länder",
    allTypes: "Alle Typen",
    minPrice: "Min. Preis (€)",
    maxPrice: "Max. Preis (€)",
    apartment: "Wohnung",
    villa: "Villa",
    penthouse: "Penthouse",
    studio: "Studio",
    townhouse: "Townhouse",
    availableOffers: "Verfügbare Angebote",
    properties: "Immobilien",
    noProperties: "Keine Immobilien gefunden",
    detail: "Details anzeigen",
    bedrooms: "Schlafzimmer",
    bathrooms: "Badezimmer",
    description: "Beschreibung",
    amenities: "Annehmlichkeiten",
    available_units: "Verfügbare Einheiten",
    interested: "Ich bin interessiert",
    nameSurname: "Name und Vorname *",
    email: "E-Mail *",
    phone: "Telefon *",
    minBudget: "Min. Budget (€)",
    maxBudget: "Max. Budget (€)",
    message: "Ihre Nachricht",
    gdpr: "Ich habe gelesen und stimme zu ",
    gdprLink: "Datenschutzrichtlinie (GDPR)",
    gdprEnd: ". Ich stimme der Verarbeitung meiner persönlichen Daten zu. *",
    send: "Anfrage senden",
    sending: "Wird gesendet...",
    listProperty: "Immobilie eintragen",
    submitTitle: "Tragen Sie Ihre Immobilie ein",
    submitSubtitle: "Geben Sie Details ein - die Anzeige wird in allen Sprachen verfügbar sein",
    submitBadge: "Kostenlose Auflistung, genehmigt innerhalb von 48 Stunden",
    ownerInfo: "Kontaktdetails",
    ownerName: "Name und Vorname",
    ownerEmail: "E-Mail",
    ownerPhone: "Telefon",
    propertyInfo: "Immobiliendetails",
    writingIn: "Schreiben in",
    propertyTitleLabel: "Immobilientitel",
    selectCountry: "Land wählen",
    cityLabel: "Stadt / Gebiet",
    typeLabel: "Immobilientyp",
    priceLabel: "Preis",
    bedroomsLabel: "Schlafzimmer",
    bathroomsLabel: "Badezimmer",
    descriptionLabel: "Immobilienbeschreibung",
    autoTranslateNote: "Wir werden die Beschreibung automatisch ins SK und EN übersetzen",
    photosLabel: "Fotos",
    uploadPhotos: "Klicken oder Fotos ziehen (max. 10)",
    submitBtn: "Zur Genehmigung einreichen",
    translatingListing: "Ihre Anzeige wird übersetzt...",
    translatingListingSub: "KI übersetzt Inhalte ins Slowakische und Englische",
    submitSuccessTitle: "Danke für Ihre Anzeige!",
    submitSuccessText: "Wir haben Ihre Anzeige erhalten und veröffentlichen sie nach Überprüfung. Sie werden per E-Mail benachrichtigt.",
    backToHome: "Zur Startseite",
    exploreMap: "Erkunden Sie unsere Ziele",
    exploreMapSub: "Klicken Sie auf die Landnadelnadel, um Angebote nach Standort zu filtern",
    rights: "Alle Rechte vorbehalten.",
    privacy: "Datenschutzrichtlinie (GDPR)",
  },
  pl: {
    offers: "Oferty",
    contact: "Kontakt",
    backToOffers: "Wróć do ofert",
    heroTitle: "Luksusowe nieruchomości",
    heroTitleHighlight: "za granicą",
    heroSubtitle: "Inwestuj w projekty premium w najlepszych celach na świecie",
    allCountries: "Wszystkie kraje",
    allTypes: "Wszystkie typy",
    minPrice: "Min. cena (€)",
    maxPrice: "Maks. cena (€)",
    apartment: "Mieszkanie",
    villa: "Willa",
    penthouse: "Penthouse",
    studio: "Studio",
    townhouse: "Townhouse",
    availableOffers: "Dostępne oferty",
    properties: "nieruchomości",
    noProperties: "Nie znaleziono nieruchomości",
    detail: "Szczegóły",
    bedrooms: "Sypialnie",
    bathrooms: "Łazienki",
    description: "Opis",
    amenities: "Udogodnienia",
    available_units: "Dostępne jednostki",
    interested: "Jestem zainteresowany",
    nameSurname: "Imię i nazwisko *",
    email: "Email *",
    phone: "Telefon *",
    minBudget: "Min. budżet (€)",
    maxBudget: "Maks. budżet (€)",
    message: "Twoja wiadomość",
    gdpr: "Przeczytałem i zgadzam się na ",
    gdprLink: "politykę ochrony danych osobowych (GDPR)",
    gdprEnd: ". Wyrażam zgodę na przetwarzanie moich danych osobowych. *",
    send: "Wyślij zapytanie",
    sending: "Wysyłanie...",
    listProperty: "Wylistuj nieruchomość",
    submitTitle: "Wylistuj swoją nieruchomość",
    submitSubtitle: "Wpisz szczegóły - ogłoszenie będzie dostępne we wszystkich językach",
    submitBadge: "Bezpłatna lista, zatwierdzamy w ciągu 48 godzin",
    ownerInfo: "Dane kontaktowe",
    ownerName: "Imię i nazwisko",
    ownerEmail: "Email",
    ownerPhone: "Telefon",
    propertyInfo: "Szczegóły nieruchomości",
    writingIn: "Piszę w języku",
    propertyTitleLabel: "Tytuł nieruchomości",
    selectCountry: "Wybierz kraj",
    cityLabel: "Miasto / obszar",
    typeLabel: "Typ nieruchomości",
    priceLabel: "Cena",
    bedroomsLabel: "Sypialnie",
    bathroomsLabel: "Łazienki",
    descriptionLabel: "Opis nieruchomości",
    autoTranslateNote: "Automatycznie przetłumaczymy opis na SK i EN",
    photosLabel: "Zdjęcia",
    uploadPhotos: "Kliknij lub przeciągnij zdjęcia (maks. 10)",
    submitBtn: "Wyślij do zatwierdzenia",
    translatingListing: "Tłumaczymy Twoją nieruchomość...",
    translatingListingSub: "AI tłumaczy zawartość na słowacki i angielski",
    submitSuccessTitle: "Dziękuję za Twoją listę!",
    submitSuccessText: "Otrzymaliśmy Twoją listę i opublikujemy ją po przejrzeniu. Powiadomimy Cię e-mailem.",
    backToHome: "Powrót do domu",
    exploreMap: "Odkryj nasze cele",
    exploreMapSub: "Kliknij szpilkę kraju, aby filtrować oferty według lokalizacji",
    rights: "Wszystkie prawa zastrzeżone.",
    privacy: "Polityka prywatności (GDPR)",
  },
  hu: {
    offers: "Ajánlatok",
    contact: "Kapcsolat",
    backToOffers: "Vissza az ajánlatokhoz",
    heroTitle: "Luxus ingatlanok",
    heroTitleHighlight: "külföldön",
    heroSubtitle: "Fektess be prémium projektokba a világ legjobb úti céljaiban",
    allCountries: "Összes ország",
    allTypes: "Összes típus",
    minPrice: "Min. ár (€)",
    maxPrice: "Max. ár (€)",
    apartment: "Lakás",
    villa: "Villa",
    penthouse: "Penthouse",
    studio: "Studio",
    townhouse: "Townhouse",
    availableOffers: "Elérhető ajánlatok",
    properties: "ingatlan",
    noProperties: "Nem találtunk ingatlanokat",
    detail: "Részletek",
    bedrooms: "Hálószobák",
    bathrooms: "Fürdőszobák",
    description: "Leírás",
    amenities: "Felszereltség",
    available_units: "Elérhető egységek",
    interested: "Érdekelt vagyok",
    nameSurname: "Név *",
    email: "E-mail *",
    phone: "Telefon *",
    minBudget: "Min. költségvetés (€)",
    maxBudget: "Max. költségvetés (€)",
    message: "Az Ön üzenete",
    gdpr: "Elolvastam és egyetértek az ",
    gdprLink: "személyes adatok védelmi irányelvével (GDPR)",
    gdprEnd: ". Beleegyezem személyes adataim feldolgozásához. *",
    send: "Lekérdezés küldése",
    sending: "Küldés folyamatban...",
    listProperty: "Ingatlan listázása",
    submitTitle: "Az Ön ingatlanának listázása",
    submitSubtitle: "Adja meg az adatokat - az objektum minden nyelven elérhető lesz",
    submitBadge: "Ingyenes listázás, 48 órán belül jóváhagyva",
    ownerInfo: "Kapcsolatadatok",
    ownerName: "Név",
    ownerEmail: "E-mail",
    ownerPhone: "Telefon",
    propertyInfo: "Ingatlan részletei",
    writingIn: "Írás nyelve",
    propertyTitleLabel: "Ingatlan címe",
    selectCountry: "Ország kiválasztása",
    cityLabel: "Város / terület",
    typeLabel: "Ingatlan típusa",
    priceLabel: "Ár",
    bedroomsLabel: "Hálószobák",
    bathroomsLabel: "Fürdőszobák",
    descriptionLabel: "Ingatlan leírása",
    autoTranslateNote: "Automatikusan lefordítjuk a leírást SK és EN nyelvekre",
    photosLabel: "Fotók",
    uploadPhotos: "Kattintson vagy húzza a fotókat (max. 10)",
    submitBtn: "Jóváhagyásra küldés",
    translatingListing: "Az Ön ingatlanát fordítjuk...",
    translatingListingSub: "Az AI lefordítja a tartalmat szlovákra és angolra",
    submitSuccessTitle: "Köszönöm az Ön listáját!",
    submitSuccessText: "Megkaptuk az Ön listáját és a felülvizsgálat után közzétesszük. E-mailben értesítjük Önt.",
    backToHome: "Vissza a kezdőoldalra",
    exploreMap: "Fedezze fel célként szolgáló helyeinket",
    exploreMapSub: "Kattintson az ország tűjére, hogy az ajánlatokat hely szerint szűrje",
    rights: "Minden jog fenntartva.",
    privacy: "Adatvédelmi irányelvek (GDPR)",
  },
  sk: {
    // Nav
    offers: "Ponuky",
    contact: "Kontakt",
    backToOffers: "Späť na ponuky",
    // Hero
    heroTitle: "Luxusné nehnuteľnosti",
    heroTitleHighlight: "v zahraničí",
    heroSubtitle: "Investujte do prémiových projektov v top destináciách sveta",
    // Filters
    allCountries: "Všetky krajiny",
    allTypes: "Všetky typy",
    minPrice: "Min. cena (€)",
    maxPrice: "Max. cena (€)",
    apartment: "Apartmán",
    villa: "Vila",
    penthouse: "Penthouse",
    studio: "Štúdio",
    townhouse: "Townhouse",
    // Listings
    availableOffers: "Dostupné ponuky",
    properties: "nehnuteľností",
    noProperties: "Nenašli sa žiadne nehnuteľnosti",
    detail: "Detail",
    // Property detail
    bedrooms: "Spálne",
    bathrooms: "Kúpeľne",
    description: "Popis",
    amenities: "Vybavenie",
    available_units: "Dostupných jednotiek",
    interested: "Mám záujem",
    nameSurname: "Meno a priezvisko *",
    email: "Email *",
    phone: "Telefón *",
    minBudget: "Min. rozpočet (€)",
    maxBudget: "Max. rozpočet (€)",
    message: "Vaša správa",
    gdpr: 'Prečítal/a som si a súhlasím s ',
    gdprLink: "podmienkami ochrany osobných údajov (GDPR)",
    gdprEnd: ". Súhlasím so spracovaním mojich osobných údajov za účelom odpovede na môj dopyt. *",
    send: "Odoslať dopyt",
    sending: "Odosielam...",
    // Submit listing
    listProperty: "Inzerovať nehnuteľnosť",
    submitTitle: "Inzerujte svoju nehnuteľnosť",
    submitSubtitle: "Zadajte detaily – inzerát bude dostupný vo všetkých jazykoch",
    submitBadge: "Bezplatné zalistovanie, schvaľujeme do 48 hodín",
    ownerInfo: "Kontaktné údaje",
    ownerName: "Meno a priezvisko",
    ownerEmail: "Email",
    ownerPhone: "Telefón",
    propertyInfo: "Detaily nehnuteľnosti",
    writingIn: "Píšem v jazyku",
    propertyTitleLabel: "Názov nehnuteľnosti",
    selectCountry: "Vyberte krajinu",
    cityLabel: "Mesto / oblasť",
    typeLabel: "Typ nehnuteľnosti",
    priceLabel: "Cena",
    bedroomsLabel: "Spálne",
    bathroomsLabel: "Kúpeľne",
    descriptionLabel: "Popis nehnuteľnosti",
    autoTranslateNote: "Popis automaticky preložíme do SK aj EN",
    photosLabel: "Fotografie",
    uploadPhotos: "Kliknite alebo presuňte fotografie (max 10)",
    submitBtn: "Odoslať na schválenie",
    translatingListing: "Prekladáme váš inzerát...",
    translatingListingSub: "AI prekladá obsah do slovenčiny a angličtiny",
    submitSuccessTitle: "Ďakujeme za inzerát!",
    submitSuccessText: "Váš inzerát sme prijali a po schválení ho zverejníme. Budeme vás informovať emailom.",
    backToHome: "Späť na úvodnú stránku",
    // Map
    exploreMap: "Preskúmajte naše destinácie",
    exploreMapSub: "Kliknite na krajinu a zobrazte ponuky v danej lokalite",
    // Footer
    rights: "Všetky práva vyhradené.",
    privacy: "Ochrana osobných údajov (GDPR)",
  },
  en: {
    // Nav
    offers: "Listings",
    contact: "Contact",
    backToOffers: "Back to listings",
    // Hero
    heroTitle: "Luxury properties",
    heroTitleHighlight: "abroad",
    heroSubtitle: "Invest in premium projects in the world's top destinations",
    // Filters
    allCountries: "All countries",
    allTypes: "All types",
    minPrice: "Min. price (€)",
    maxPrice: "Max. price (€)",
    apartment: "Apartment",
    villa: "Villa",
    penthouse: "Penthouse",
    studio: "Studio",
    townhouse: "Townhouse",
    // Listings
    availableOffers: "Available listings",
    properties: "properties",
    noProperties: "No properties found",
    detail: "View",
    // Property detail
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    description: "Description",
    amenities: "Amenities",
    available_units: "Available units",
    interested: "I'm interested",
    nameSurname: "Full name *",
    email: "Email *",
    phone: "Phone *",
    minBudget: "Min. budget (€)",
    maxBudget: "Max. budget (€)",
    message: "Your message",
    gdpr: "I have read and agree to the ",
    gdprLink: "personal data protection policy (GDPR)",
    gdprEnd: ". I consent to the processing of my personal data for the purpose of responding to my inquiry. *",
    send: "Send inquiry",
    sending: "Sending...",
    // Submit listing
    listProperty: "List a property",
    submitTitle: "List your property",
    submitSubtitle: "Enter details in your language – we'll automatically translate to SK and EN",
    submitBadge: "Free listing, approved within 48 hours",
    ownerInfo: "Contact details",
    ownerName: "Full name",
    ownerEmail: "Email",
    ownerPhone: "Phone",
    propertyInfo: "Property details",
    writingIn: "Writing in",
    propertyTitleLabel: "Property title",
    selectCountry: "Select country",
    cityLabel: "City / area",
    typeLabel: "Property type",
    priceLabel: "Price",
    bedroomsLabel: "Bedrooms",
    bathroomsLabel: "Bathrooms",
    descriptionLabel: "Property description",
    autoTranslateNote: "We will automatically translate the description to both SK and EN",
    photosLabel: "Photos",
    uploadPhotos: "Click or drag photos (max 10)",
    submitBtn: "Submit for approval",
    translatingListing: "Translating your listing...",
    translatingListingSub: "AI is translating content to Slovak and English",
    submitSuccessTitle: "Thank you for your listing!",
    submitSuccessText: "We have received your listing and will publish it after review. You will be notified by email.",
    backToHome: "Back to home",
    // Map
    exploreMap: "Explore our destinations",
    exploreMapSub: "Click a country pin to filter listings by location",
    // Footer
    rights: "All rights reserved.",
    privacy: "Privacy Policy (GDPR)",
  },
};

const PublicLanguageContext = createContext();

export function PublicLanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("pub_lang") || "sk");

  const changeLang = (l) => {
    localStorage.setItem("pub_lang", l);
    setLang(l);
  };

  const tr = (key) => t[lang]?.[key] || key;

  return (
    <PublicLanguageContext.Provider value={{ lang, changeLang, tr }}>
      {children}
    </PublicLanguageContext.Provider>
  );
}

export function usePublicLang() {
  return useContext(PublicLanguageContext);
}